### ISSUE TITLE
Can't see the controller in UE 4.11.2

### ISSUE THREAD

**Issue by coolguji** [CJRobertson/HTCViveTemplate-UE4#6]
I just download the package and Open it with UE 4.11.2 then hit play.
But I can't see the controller in my view.
So did the project fit the UE 4.11.2?

**Comment by whynot83** [comment]
https://docs.unrealengine.com/latest/INT/Platforms/SteamVR/QuickStart/2/index.html

scroll down to step 3. '...right - click inside of the Content Browser and select the Blueprint Class option from the Create Basic Asset section.'  Follow steps 3-6 for creating a VR_GameMode blueprint and hooking it up.   After that I could see the controllers.
